// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzlaG6vqfEPW9DTJhOqkFxPYXyrSf5OQk',
    appId: '1:536109698393:web:f11cbce66acf76f70a1048',
    messagingSenderId: '536109698393',
    projectId: 'home-720ef',
    authDomain: 'home-720ef.firebaseapp.com',
    storageBucket: 'home-720ef.firebasestorage.app',
    measurementId: 'G-854HQ1ZV80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh3YAaUFyTwZLqhlcrCH5f5BtT4hDpWMs',
    appId: '1:536109698393:android:90dfa5536d3c61f70a1048',
    messagingSenderId: '536109698393',
    projectId: 'home-720ef',
    storageBucket: 'home-720ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQRkHRLsXiOzSferecqnT2aBjzq_XgnLM',
    appId: '1:536109698393:ios:24c98a32dcf26eef0a1048',
    messagingSenderId: '536109698393',
    projectId: 'home-720ef',
    storageBucket: 'home-720ef.firebasestorage.app',
    iosBundleId: 'com.example.yshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQRkHRLsXiOzSferecqnT2aBjzq_XgnLM',
    appId: '1:536109698393:ios:24c98a32dcf26eef0a1048',
    messagingSenderId: '536109698393',
    projectId: 'home-720ef',
    storageBucket: 'home-720ef.firebasestorage.app',
    iosBundleId: 'com.example.yshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzlaG6vqfEPW9DTJhOqkFxPYXyrSf5OQk',
    appId: '1:536109698393:web:b0cd0b6fa1231c1f0a1048',
    messagingSenderId: '536109698393',
    projectId: 'home-720ef',
    authDomain: 'home-720ef.firebaseapp.com',
    storageBucket: 'home-720ef.firebasestorage.app',
    measurementId: 'G-6WMMECR2GM',
  );
}
